#
#  Podfile
#
#  Copyright (c) 2019 Netguru Sp. z o.o. All rights reserved.
#

# Pod sources
source 'https://github.com/CocoaPods/Specs.git'

# Initial configuration
platform :ios, '14.1'
use_frameworks!
inhibit_all_warnings!

project 'iosApp'

target 'iosApp' do
  pod 'SwiftFormat/CLI', '~> 0.47.11'
  pod 'SwiftLint', '~> 0.47.1'
  
  target 'iosAppTests' do
    inherit! :search_paths
	 
	 pod 'Mimus', :git => 'https://github.com/mimus-swift/Mimus', :commit => 'fca9cd6ac22e08ac397c4ab4415fe849bd377cc8'
	 pod 'SnapshotTesting', "~> 1.9.0"
  end
end

# https://stackoverflow.com/a/63489366/13780695

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
